#!/bin/bash

set -eo pipefail

ROOT=$(pwd)
GOCMD=${GOCMD:=go}
BKLTMP=$(mktemp -d)
BINS="bkl bkld bkli bklr"

function cleanup {
	rm -Rf $BKLTMP $TESTTMP
}

for BIN in $BINS; do
	$GOCMD build -o $BKLTMP/$BIN ./cmd/$BIN
done

export PATH=$BKLTMP:$PATH

FOUND=n

for TEST in tests/*; do
	if [[ "$1" != "" && "tests/$1" != "$TEST" ]]; then
		continue
	fi

	FOUND=y

	echo TEST $TEST
	cd $TEST

	TESTTMP=$(mktemp -d)

  set +e
  if ! source cmd >/dev/null 2>&1; then
    printf "	\e[31mFAIL\e[0m\n"
    source cmd
    cleanup
    exit 1
  fi
  set -e

	diff -ud expected <(source cmd 2>/dev/null)

	cd ~-
	printf "	\e[32mPASS\e[0m\n"

	rm -Rf $TESTTMP
done

cleanup

if [[ "$1" != "" && $FOUND == n ]]; then
	echo "No test matching '$1' found"
	exit 1
fi