#!/bin/bash

set -euo pipefail

ROOT=$(pwd)
GOCMD=${GOCMD:=go}
BINS="bkl bkli bkld"

function cleanup {
	for BIN in $BINS; do
		rm $ROOT/$BIN
	done
}

trap cleanup EXIT

for BIN in $BINS; do
	$GOCMD build ./cmd/$BIN
done

export PATH=$ROOT:$PATH

for TEST in tests/*; do
	echo TEST $TEST
	cd $TEST

	diff -ud expected <(source cmd)

	cd ~-
	echo "	PASS"
done
