#!/bin/bash

set -euo pipefail

ROOT=$(pwd)
GOCMD=${GOCMD:=go}

function cleanup {
	rm $ROOT/bkl{,i}
}

trap cleanup EXIT

$GOCMD build ./cmd/bkl
$GOCMD build ./cmd/bkli
export PATH=$ROOT:$PATH

for TEST in tests/*; do
	echo TEST $TEST
	cd $TEST

	diff -ud expected <(source cmd)

	cd ~-
	echo "	PASS"
done
